# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
# import data

df = pd.read_csv("data/Churn_Modelling.csv")
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Creating a new column

In [31]:
data = {
  "age": [16, 14, 10],
  "qualified": [True, True, True]
}
data = pd.DataFrame(data)

newdf = data.assign(name = ["Emil", "Tobias", "Linus"])

In [32]:
newdf

   age  qualified    name
0   16       True    Emil
1   14       True  Tobias
2   10       True   Linus

In [3]:
# Add 1000 to the column values and assign to a new column
df['New Balance'] = df['Balance'] + 1000

In [5]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82

### Dropping NA values

In [33]:
# Check for null values

df.isnull()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [30]:
# NA values in a column

print(df['Gender'].isna().sum())

0

In [6]:
new_df = df.dropna()

print(new_df.head(5))

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1

   EstimatedSalary  Exited  New Balance
0        101348.88       1      1000.00
1        112542.58       0     84807.86
2        113931.57       1    160660.80
3         93826.63       0      1000.00
4         79084.10       0    126510.82

In [7]:
# To change original data:
df.dropna(inplace = True)

In [8]:
# To fill NAs with a value
df.fillna(130, inplace = True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [9]:
# Fill NAs in Geography column with Ghana

df.fillna({"Geography": "Ghana"}, inplace=True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [10]:
# Fill NAs with the mean value

x = df["Tenure"].mean()

df.fillna({"Tenure": x}, inplace=True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [11]:
# Fill NAs with the median value

x = df["Tenure"].median()

df.fillna({"Tenure": x}, inplace=True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [12]:
# Fill NAs with the mode value

x = df["Tenure"].mode()[0] # the value that appears most frequently

df.fillna({"Tenure": x}, inplace=True)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1000.00
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,84807.86
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,160660.80
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1000.00
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,126510.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,1000.00
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,58369.61
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1000.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,76075.31
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [14]:
# Filter Age < 30

df1 = df[df['Age'] < 30]
df1

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,116046.74
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,135603.88
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0,1000.00
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0,1000.00
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0,1000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0,1000.00
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0,1000.00
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0,156060.41
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0,1000.00
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

In [16]:
# Alternatively
df2 = df[df.Age < 30]
df2

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,116046.74
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,135603.88
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0,1000.00
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0,1000.00
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0,1000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0,1000.00
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0,1000.00
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0,156060.41
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0,1000.00
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,131142.79

### Removing Duplicates

In [17]:
# Returns True for every row that is a duplicate, otherwise False

print(df.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [18]:
# To remove duplicates

df.drop_duplicates(inplace = True)

### Remove a column

In [19]:
df2.pop("CreditScore")
df2.head()

,RowNumber,CustomerId,Surname,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance
7,8,15656148,Obinna,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,116046.74
9,10,15592389,H?,France,Male,27,2,134603.88,1,1,1,71725.73,0,135603.88
11,12,15737173,Andrews,Spain,Male,24,3,0.00,2,1,0,76390.01,0,1000.00
13,14,15691483,Chin,France,Female,25,5,0.00,2,0,0,190857.79,0,1000.00
17,18,15788218,Henderson,Spain,Female,24,9,0.00,2,1,1,14406.41,0,1000.00

### Mathematical Operations on data

In [23]:
# Apply square root to a column

df3 = df2['New Balance'].apply(np.sqrt)
df3.head()

7     340.656337
9     368.244321
11     31.622777
13     31.622777
17     31.622777
Name: New Balance, dtype: float64

## loc vs iloc

.loc (Label-based): You use the names (labels) of rows and columns.

.iloc (Integer-based): You use the position (0, 1, 2...)—just like a standard Python list.

### 1. Using .loc (Label-based)

Syntax: df.loc[row_label, column_label]

In [35]:
df = pd.DataFrame({
    'Sales': [10, 20, 30],
    'Inventory': [100, 150, 200]
}, index=['Store_A', 'Store_B', 'Store_C'])

df

         Sales  Inventory
Store_A     10        100
Store_B     20        150
Store_C     30        200

In [37]:
# Get Sales for Store_B
val = df.loc['Store_B', 'Sales'] # Result: 20
print(val)

20

In [38]:
# Get everything for Store_A and Store_C
subset = df.loc[['Store_A', 'Store_C'], :]
print(subset)

         Sales  Inventory
Store_A     10        100
Store_C     30        200

In [39]:
# Slicing (Note: In .loc, the end is INCLUDED)
slice_df = df.loc['Store_A':'Store_B', 'Sales'] # Includes Store_B
print(slice_df)

Store_A    10
Store_B    20
Name: Sales, dtype: int64

### 2. Using .iloc (Integer-based)

Syntax: df.iloc[row_index, column_index]

In [40]:
# Get the first row, first column
val2 = df.iloc[0, 0] # Result: 10
print(val2)

10

In [41]:
# Get the last row (using -1 like a list)
last_row = df.iloc[-1, :]
print(last_row)

Sales         30
Inventory    200
Name: Store_C, dtype: int64

In [42]:
# Slicing (Note: In .iloc, the end is EXCLUDED, standard Python style)
slice_df2 = df.iloc[0:2, 0:1] # Gets rows 0, 1 and column 0 (excludes 2)
print(slice_df2)

         Sales
Store_A     10
Store_B     20

### Boolean Indexing

.loc is the standard way to filter rows based on conditions

In [43]:
# Select all stores where Sales are greater than 15
high_sales = df.loc[df['Sales'] > 15, :]
high_sales

         Sales  Inventory
Store_B     20        150
Store_C     30        200