# Using concat()

In [2]:
import pandas as pd
import numpy as np

In [3]:
# combine two Series... default is by rows

s1 = pd.Series(["a", "b"])
s2 = pd.Series(["c", "d"])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: str

In [4]:
# ignoring the original index

pd.concat([s1, s2], ignore_index=True)

0    a
1    b
2    c
3    d
dtype: str

In [5]:
# Labeling the index

pd.concat([s1, s2], keys=["s1", "s2"], names=["Series name", "Row ID"])

Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: str

In [8]:
# combine two Series by column

s3 = pd.Series(["a", "b"])
s4 = pd.Series(["c", "d"])
df1 = pd.concat([s3, s4], axis = 1)
df1

   0  1
0  a  c
1  b  d

In [11]:
df1 = pd.DataFrame([["a", 1], ["b", 2]], columns=["letter", "number"])
df1

  letter  number
0      a       1
1      b       2

In [9]:
df3 = pd.DataFrame(
    [["c", 3, "cat"], ["d", 4, "dog"]], columns=["letter", "number", "animal"])
df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [12]:
pd.concat([df1, df3], sort=False)

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [14]:
# Append a DataFrame at the end of another DataFrame

data1 = {
  "age": [16, 14, 10],
  "qualified": [True, True, True]
}
df1 = pd.DataFrame(data1)
df1

   age  qualified
0   16       True
1   14       True
2   10       True

In [15]:
data2 = {
  "age": [55, 40],
  "qualified": [True, False]
}
df2 = pd.DataFrame(data2)
df2

   age  qualified
0   55       True
1   40      False

In [18]:
newdf = pd.concat([df1, df2])
newdf

   age  qualified
0   16       True
1   14       True
2   10       True
0   55       True
1   40      False