## 1. Group by

The groupby() method allows you to group your data and execute functions on these groups.

In [2]:
import pandas as pd
import numpy as np

In [7]:
# Sample sales data
df = pd.DataFrame({
    'Category': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home'],
    'Sales': [200, 150, 100, 80, 300],
    'Profit': [50, 40, 20, 15, 70]
})

# Group by Category and sum the numeric columns
grouped_sum = df.groupby('Category').sum()
grouped_sum

             Sales  Profit
Category
Clothing       180      35
Electronics    350      90
Home           300      70

In [10]:
# groupby multiple columns

df.groupby(['Category', 'Sales']).mean()

                   Profit
Category    Sales
Clothing    80       15.0
            100      20.0
Electronics 150      40.0
            200      50.0
Home        300      70.0

In [11]:
# Sum of sales and average of profit
df.groupby('Category').agg({'Sales': 'sum', 'Profit': 'mean'})

             Sales  Profit
Category
Clothing       180    17.5
Electronics    350    45.0
Home           300    70.0

In [12]:
# keep index

df.groupby('Category', as_index=False).sum()

      Category  Sales  Profit
0     Clothing    180      35
1  Electronics    350      90
2         Home    300      70

## 2. Transform (.transform)

Use this when you want to perform a group-based calculation but keep the result the same length as your original DataFrame. It’s perfect for normalizing data.

In [13]:
df = pd.DataFrame({
    'Team': ['A', 'A', 'B', 'B', 'C'],
    'Score': [10, 20, 40, 50, 100]
})

# Calculate the group mean and "broadcast" it to every row
df['Team_Avg'] = df.groupby('Team')['Score'].transform('mean')

# calculate how much each row deviates from its team average
df['Deviation'] = df['Score'] - df['Team_Avg']
df

  Team  Score  Team_Avg  Deviation
0    A     10      15.0       -5.0
1    A     20      15.0        5.0
2    B     40      45.0       -5.0
3    B     50      45.0        5.0
4    C    100     100.0        0.0

## 3. Filter (.filter)

This allows you to drop entire groups based on a condition. For example, if you only want to see data from teams that have a high average score.

In [14]:
# Keep only teams where the average score is greater than 20
# Team A (avg 15) will be removed; Team B and C will stay.
filtered_df = df.groupby('Team').filter(lambda x: x['Score'].mean() > 20)
filtered_df

  Team  Score  Team_Avg  Deviation
2    B     40      45.0       -5.0
3    B     50      45.0        5.0
4    C    100     100.0        0.0

## 4. Apply (.apply)

For complex logic

In [16]:
df = pd.DataFrame({
    'Team': ['A', 'A', 'B', 'B', 'C'],
    'Score': [10, 20, 40, 50, 100]
})

# Get the top 1 scorer for each team
def get_top_scorer(group):
    return group.nlargest(1, 'Score')

top_scorers = df.groupby('Team').apply(get_top_scorer)
top_scorers

        Score
Team
A    1     20
B    3     50
C    4    100